version: '3.8'

services:
  api:
    build: .
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://neondb_owner:npg_la7fbzc2edpt@ep-delicate-salad-a2lp8acq-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require
      WEATHER_API_KEY: 5ce16ef810ff4586880184644251505
      EMAIL_HOST: smtp.mailgun.org
      EMAIL_PORT: 587
      EMAIL_USER: postmaster@sandbox7e4403b356a244969709915ce43634dd.mailgun.org
      EMAIL_PASS: bc40c47724d467a0d583ae7c800bf6e6-f3238714-e44137be
      BASE_URL: http://localhost:3000

      MAILGUN_API_KEY: 1b6b94fdb448cb8ecd43be1316079f76-f3238714-8779d6a3
      MAILGUN_DOMAIN: sandbox7e4403b356a244969709915ce43634dd.mailgun.org
    ports:
      - "3000:3000"
    command: ["node", "./src/index.js"]
    volumes:
      - .:/app
